### ISSUE TITLE
Tag 249 missing

### ISSUE THREAD

**Issue by olalonde** [thisismattmiller/marc-json-schema#1]
I noticed that the tag 249 is not part of the schema. Is there any specific reason for that? Is it not part of the documentation?

Thanks.

**Comment by caiosm1005** [comment]
@olalonde Apparently, it is not part of the official documentation.
https://www.loc.gov/marc/bibliographic/bd20x24x.html

Current 20X-24X fields are:

```
210 - Abbreviated Title (R)
222 - Key Title (R)
240 - Uniform Title (NR)
242 - Translation of Title by Cataloging Agency (R)
243 - Collective Uniform Title (NR)
245 - Title Statement (NR)
246 - Varying Form of Title (R)
247 - Former Title (R)
```

**Comment by olalonde** [comment]
Thanks
